### ISSUE TITLE
Testing for validity

### ISSUE THREAD

**Issue by Ciheim** [aradhakrishnanGFDL/CatalogBuilder#106]
There is a need for a testing script that can verify each catalog + json pair is Intake-ESM compatible.

**Comment by aradhakrishnanGFDL** [comment]
@Ciheim, we have some preliminary pytests as part of the CI pipeline. Leverage this structure, so you can expand and add it to the CI and pytests. The issue needs a list of sub-issues or bullets to indicate  what verifying is needed, in addition to what currently exists. 

https://github.com/aradhakrishnanGFDL/CatalogBuilder/actions/runs/8236398738/job/22522712762#step:10:53

**Comment by Ciheim** [comment]
- [ ] Ensure that all required headers exist
- [ ] Ensure that all optional headers exist
- [ ] Ensure that no value in a required column is empty
- [ ] Establish clear distinction between default and 'extended' cataloging
