### ISSUE TITLE
clean repo

### ISSUE THREAD

**Issue by aradhakrishnanGFDL** [aradhakrishnanGFDL/CatalogBuilder#133]
Lets clean up the repository and remove unused files to prepare to transition to NOAA-GFDL org.

e.g. https://github.com/aradhakrishnanGFDL/CatalogBuilder/tree/106.Testing/cats 

the *test1.csv etc could be removed

**Comment by aradhakrishnanGFDL** [comment]
@Ciheim I am starting to do some housekeeping on this repo. I removed gfdl_test1.json, but notice its being used here https://github.com/aradhakrishnanGFDL/CatalogBuilder/blob/1c7bd5b53552dbc1ecfc59b200369215ebd18152/tests/test_ingestion.py#L24

How is test_ingestion used in the repo today? Can gfdl_template.json be used instead?

**Comment by Ciheim** [comment]
test_ingestion already existed in the repo as test_catalog. I'm not sure where it's currently being used.

It doesn't seem like the switch would break the script though.
