### ISSUE TITLE
Integrate catalog builder with fre-cli: To use with Canopy

### ISSUE THREAD

**Issue by ceblanton** [aradhakrishnanGFDL/CatalogBuilder#29]
We (the FRE team) plan to make most FRE capability available in dual command-line (bash) and python interfaces. While the fre-cli project is getting started, the "fre SUBCOMMAND COMMAND" style of usage will be used. So we can begin to brainstorm and draft catalog-related tool usage in that context. Mechanically, the code could be added from this repository to fre-cli as a submodule, preserving the catalog builder's independence and utility outside of GFDL and FRE.

Currently, we have one verb: building a catalog. Will there be others? If only one, maybe it could be a subcommand of "fre pp". Or if there are a few verbs (validating, inspecting?) then maybe it should have a subcommand noun of its own: "fre catalog generate".

**Comment by aradhakrishnanGFDL** [comment]
@bcc2761 @ceblanton mark this as complete once docs are ready.

**Comment by Ciheim** [comment]
Initial setup is complete and documented: https://aradhakrishnangfdl.github.io/CatalogBuilder/generation.html#using-fre-cli-gfdl-only

Further catalog builder progress in relation to fre-cli can be tracked here: https://github.com/NOAA-GFDL/fre-cli/issues
